Fixed typo in .travis.yml

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,10 +24,10 @@ script:
     RETRIES=10;
     TIMEOUT=1;
     while [[ true ]]; do
-      ((RETRIES--));
       echo "Waiting for response from server... $RETRIES";
       sleep $TIMEOUT;
       curl -sS -X POST http://localhost:${SERVER_PORT}/hook;
       if [[ "$?" = "0" ]]; then echo "Server responded!"; break; fi;
-      if [[ "$TRIES" -le "0" ]]; then echo "Failed to contact server."; exit 1; break; fi;
+      if [[ "$RETRIES" -le "0" ]]; then echo "Failed to contact server."; exit 1; break; fi;
+      ((RETRIES--));
     done;
